id: I1E4538F5
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3878final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:46:33.067629'
last_modified: '2022-08-01T10:46:33.067665'
parser: null
source_metadata:
  title: ཐུང་མོང་གི་རྩ་བ།txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
